version: '3.9'

services:
  postgres_primary:
    image: postgres:16.1
    container_name: postgres_primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  postgres_replica1:
    build:
      context: .
      dockerfile: Dockerfile.replica
    container_name: postgres_replica1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_replica1_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  postgres_replica2:
    build:
      context: .
      dockerfile: Dockerfile.replica
    container_name: postgres_replica2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_replica2_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_primary_data:
    driver: local
  postgres_replica1_data:
    driver: local
  postgres_replica2_data:
    driver: local

networks:
  postgres_network:
    driver: bridge


# version: '3.9'

# services:
#   postgres_primary:
#     image: postgres:16.1
#     container_name: postgres_primary
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: mysecretpassword
#     volumes:
#       - postgres_primary_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     networks:
#       - postgres_network

#   postgres_replica1:
#     image: postgres:16.1
#     container_name: postgres_replica1
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: mysecretpassword
#     volumes:
#       - postgres_replica1_data:/var/lib/postgresql/data
#     networks:
#       - postgres_network

#   postgres_replica2:
#     image: postgres:16.1
#     container_name: postgres_replica2
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: mysecretpassword
#     volumes:
#       - postgres_replica2_data:/var/lib/postgresql/data
#     networks:
#       - postgres_network

# volumes:
#   postgres_primary_data:
#     driver: local
#   postgres_replica1_data:
#     driver: local
#   postgres_replica2_data:
#     driver: local

# networks:
#   postgres_network:
#     driver: bridge
